"""Add Phase 1 Agent metrics tables

Revision ID: e2554661854a
Revises: None
Create Date: 2026-07-02 19:07:18.560262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2554661854a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase1_metric_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Double(), nullable=False),
    sa.Column('memory_bytes', sa.BigInteger(), nullable=False),
    sa.Column('memory_mb', sa.Double(), nullable=False),
    sa.Column('memory_gb', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['hexa.machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hexa'
    )
    op.create_index(op.f('ix_hexa_phase1_metric_reports_id'), 'phase1_metric_reports', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_phase1_metric_reports_machine_id'), 'phase1_metric_reports', ['machine_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_phase1_metric_reports_timestamp'), 'phase1_metric_reports', ['timestamp'], unique=False, schema='hexa')
    op.create_table('phase1_gpu_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('core_count', sa.Integer(), nullable=True),
    sa.Column('metal_supported', sa.Boolean(), nullable=True),
    sa.Column('metal_family', sa.String(length=100), nullable=True),
    sa.Column('utilization', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['hexa.phase1_metric_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hexa'
    )
    op.create_index(op.f('ix_hexa_phase1_gpu_metrics_id'), 'phase1_gpu_metrics', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_phase1_gpu_metrics_report_id'), 'phase1_gpu_metrics', ['report_id'], unique=True, schema='hexa')
    op.create_table('phase1_storage_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('project_bytes', sa.BigInteger(), nullable=False),
    sa.Column('project_mb', sa.Double(), nullable=False),
    sa.Column('project_gb', sa.Double(), nullable=False),
    sa.Column('backend_bytes', sa.BigInteger(), nullable=False),
    sa.Column('backend_mb', sa.Double(), nullable=False),
    sa.Column('backend_gb', sa.Double(), nullable=False),
    sa.Column('frontend_bytes', sa.BigInteger(), nullable=False),
    sa.Column('frontend_mb', sa.Double(), nullable=False),
    sa.Column('frontend_gb', sa.Double(), nullable=False),
    sa.Column('uploads_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploads_mb', sa.Double(), nullable=False),
    sa.Column('uploads_gb', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['hexa.phase1_metric_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hexa'
    )
    op.create_index(op.f('ix_hexa_phase1_storage_metrics_id'), 'phase1_storage_metrics', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_phase1_storage_metrics_report_id'), 'phase1_storage_metrics', ['report_id'], unique=True, schema='hexa')
    op.drop_constraint(op.f('agents_machine_id_key'), 'agents', schema='hexa', type_='unique')
    op.drop_constraint(op.f('agents_token_hash_key'), 'agents', schema='hexa', type_='unique')
    op.drop_index(op.f('idx_agents_machine_id'), table_name='agents', schema='hexa')
    op.drop_index(op.f('idx_agents_token_hash'), table_name='agents', schema='hexa')
    op.create_index(op.f('ix_hexa_agents_id'), 'agents', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_agents_machine_id'), 'agents', ['machine_id'], unique=True, schema='hexa')
    op.create_index(op.f('ix_hexa_agents_token_hash'), 'agents', ['token_hash'], unique=True, schema='hexa')
    op.drop_index(op.f('idx_alert_rules_environment_id'), table_name='alert_rules', schema='hexa')
    op.create_index(op.f('ix_hexa_alert_rules_environment_id'), 'alert_rules', ['environment_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_alert_rules_id'), 'alert_rules', ['id'], unique=False, schema='hexa')
    op.drop_index(op.f('idx_alerts_alert_rule_id'), table_name='alerts', schema='hexa')
    op.drop_index(op.f('idx_alerts_api_check_id'), table_name='alerts', schema='hexa')
    op.drop_index(op.f('idx_alerts_incident_id'), table_name='alerts', schema='hexa')
    op.drop_index(op.f('idx_alerts_machine_id'), table_name='alerts', schema='hexa')
    op.drop_index(op.f('idx_alerts_service_id'), table_name='alerts', schema='hexa')
    op.drop_index(op.f('idx_alerts_unresolved'), table_name='alerts', schema='hexa', postgresql_where='(resolved_at IS NULL)')
    op.create_index(op.f('ix_hexa_alerts_alert_rule_id'), 'alerts', ['alert_rule_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_alerts_api_check_id'), 'alerts', ['api_check_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_alerts_id'), 'alerts', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_alerts_incident_id'), 'alerts', ['incident_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_alerts_machine_id'), 'alerts', ['machine_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_alerts_resolved_at'), 'alerts', ['resolved_at'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_alerts_service_id'), 'alerts', ['service_id'], unique=False, schema='hexa')
    op.drop_index(op.f('idx_api_check_history_composite'), table_name='api_check_history', schema='hexa')
    op.drop_index(op.f('idx_api_check_history_fk'), table_name='api_check_history', schema='hexa')
    op.drop_index(op.f('idx_api_check_history_timestamp'), table_name='api_check_history', schema='hexa')
    op.create_index(op.f('ix_hexa_api_check_history_api_check_id'), 'api_check_history', ['api_check_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_api_check_history_id'), 'api_check_history', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_api_check_history_timestamp'), 'api_check_history', ['timestamp'], unique=False, schema='hexa')
    op.alter_column('api_checks', 'headers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='hexa')
    op.drop_index(op.f('idx_api_checks_environment_id'), table_name='api_checks', schema='hexa')
    op.create_index(op.f('ix_hexa_api_checks_environment_id'), 'api_checks', ['environment_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_api_checks_id'), 'api_checks', ['id'], unique=False, schema='hexa')
    op.drop_index(op.f('idx_environments_project_id'), table_name='environments', schema='hexa')
    op.create_index(op.f('ix_hexa_environments_id'), 'environments', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_environments_project_id'), 'environments', ['project_id'], unique=False, schema='hexa')
    op.drop_index(op.f('idx_heartbeats_agent_id'), table_name='heartbeats', schema='hexa')
    op.drop_index(op.f('idx_heartbeats_agent_timestamp'), table_name='heartbeats', schema='hexa')
    op.drop_index(op.f('idx_heartbeats_timestamp_desc'), table_name='heartbeats', schema='hexa')
    op.create_index(op.f('ix_hexa_heartbeats_agent_id'), 'heartbeats', ['agent_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_heartbeats_id'), 'heartbeats', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_heartbeats_timestamp'), 'heartbeats', ['timestamp'], unique=False, schema='hexa')
    op.drop_index(op.f('idx_incidents_environment_id'), table_name='incidents', schema='hexa')
    op.drop_index(op.f('idx_incidents_started'), table_name='incidents', schema='hexa')
    op.drop_index(op.f('idx_incidents_status'), table_name='incidents', schema='hexa')
    op.create_index(op.f('ix_hexa_incidents_environment_id'), 'incidents', ['environment_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_incidents_id'), 'incidents', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_incidents_started_at'), 'incidents', ['started_at'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_incidents_status'), 'incidents', ['status'], unique=False, schema='hexa')
    op.alter_column('logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='hexa')
    op.drop_index(op.f('idx_logs_machine_id'), table_name='logs', schema='hexa')
    op.drop_index(op.f('idx_logs_query'), table_name='logs', schema='hexa')
    op.drop_index(op.f('idx_logs_service_id'), table_name='logs', schema='hexa')
    op.drop_index(op.f('idx_logs_severity'), table_name='logs', schema='hexa')
    op.drop_index(op.f('idx_logs_timestamp'), table_name='logs', schema='hexa')
    op.create_index(op.f('ix_hexa_logs_id'), 'logs', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_logs_machine_id'), 'logs', ['machine_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_logs_service_id'), 'logs', ['service_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_logs_severity'), 'logs', ['severity'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_logs_timestamp'), 'logs', ['timestamp'], unique=False, schema='hexa')
    op.drop_index(op.f('idx_metrics_composite'), table_name='machine_metrics', schema='hexa')
    op.drop_index(op.f('idx_metrics_machine_id'), table_name='machine_metrics', schema='hexa')
    op.drop_index(op.f('idx_metrics_timestamp_desc'), table_name='machine_metrics', schema='hexa')
    op.create_index(op.f('ix_hexa_machine_metrics_id'), 'machine_metrics', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_machine_metrics_machine_id'), 'machine_metrics', ['machine_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_machine_metrics_timestamp'), 'machine_metrics', ['timestamp'], unique=False, schema='hexa')
    op.drop_index(op.f('idx_machines_environment_id'), table_name='machines', schema='hexa')
    op.create_index(op.f('ix_hexa_machines_environment_id'), 'machines', ['environment_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_machines_id'), 'machines', ['id'], unique=False, schema='hexa')
    op.drop_constraint(op.f('projects_name_key'), 'projects', schema='hexa', type_='unique')
    op.create_index(op.f('ix_hexa_projects_id'), 'projects', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_projects_name'), 'projects', ['name'], unique=True, schema='hexa')
    op.drop_index(op.f('idx_scheduler_jobs_machine_id'), table_name='scheduler_jobs', schema='hexa')
    op.create_index(op.f('ix_hexa_scheduler_jobs_id'), 'scheduler_jobs', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_scheduler_jobs_machine_id'), 'scheduler_jobs', ['machine_id'], unique=False, schema='hexa')
    op.drop_index(op.f('idx_scheduler_runs_composite'), table_name='scheduler_runs', schema='hexa')
    op.drop_index(op.f('idx_scheduler_runs_job_id'), table_name='scheduler_runs', schema='hexa')
    op.create_index(op.f('ix_hexa_scheduler_runs_id'), 'scheduler_runs', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_scheduler_runs_job_id'), 'scheduler_runs', ['job_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_scheduler_runs_started_at'), 'scheduler_runs', ['started_at'], unique=False, schema='hexa')
    op.drop_index(op.f('idx_svc_hist_composite'), table_name='service_status_history', schema='hexa')
    op.drop_index(op.f('idx_svc_hist_service_id'), table_name='service_status_history', schema='hexa')
    op.drop_index(op.f('idx_svc_hist_timestamp'), table_name='service_status_history', schema='hexa')
    op.create_index(op.f('ix_hexa_service_status_history_id'), 'service_status_history', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_service_status_history_service_id'), 'service_status_history', ['service_id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_service_status_history_timestamp'), 'service_status_history', ['timestamp'], unique=False, schema='hexa')
    op.drop_index(op.f('idx_services_machine_id'), table_name='services', schema='hexa')
    op.create_index(op.f('ix_hexa_services_id'), 'services', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_services_machine_id'), 'services', ['machine_id'], unique=False, schema='hexa')
    op.drop_index(op.f('idx_sessions_refresh_token'), table_name='sessions', schema='hexa')
    op.drop_index(op.f('idx_sessions_user_id'), table_name='sessions', schema='hexa')
    op.drop_constraint(op.f('sessions_refresh_token_key'), 'sessions', schema='hexa', type_='unique')
    op.create_index(op.f('ix_hexa_sessions_id'), 'sessions', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_sessions_refresh_token'), 'sessions', ['refresh_token'], unique=True, schema='hexa')
    op.create_index(op.f('ix_hexa_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='hexa')
    op.drop_index(op.f('idx_settings_key'), table_name='settings', schema='hexa')
    op.drop_constraint(op.f('settings_key_key'), 'settings', schema='hexa', type_='unique')
    op.create_index(op.f('ix_hexa_settings_id'), 'settings', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_settings_key'), 'settings', ['key'], unique=True, schema='hexa')
    op.drop_index(op.f('idx_users_email'), table_name='users', schema='hexa')
    op.drop_index(op.f('idx_users_username'), table_name='users', schema='hexa')
    op.drop_constraint(op.f('users_email_key'), 'users', schema='hexa', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', schema='hexa', type_='unique')
    op.create_index(op.f('ix_hexa_users_email'), 'users', ['email'], unique=True, schema='hexa')
    op.create_index(op.f('ix_hexa_users_id'), 'users', ['id'], unique=False, schema='hexa')
    op.create_index(op.f('ix_hexa_users_username'), 'users', ['username'], unique=True, schema='hexa')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hexa_users_username'), table_name='users', schema='hexa')
    op.drop_index(op.f('ix_hexa_users_id'), table_name='users', schema='hexa')
    op.drop_index(op.f('ix_hexa_users_email'), table_name='users', schema='hexa')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], schema='hexa', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], schema='hexa', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False, schema='hexa')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_settings_key'), table_name='settings', schema='hexa')
    op.drop_index(op.f('ix_hexa_settings_id'), table_name='settings', schema='hexa')
    op.create_unique_constraint(op.f('settings_key_key'), 'settings', ['key'], schema='hexa', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_settings_key'), 'settings', ['key'], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_sessions_user_id'), table_name='sessions', schema='hexa')
    op.drop_index(op.f('ix_hexa_sessions_refresh_token'), table_name='sessions', schema='hexa')
    op.drop_index(op.f('ix_hexa_sessions_id'), table_name='sessions', schema='hexa')
    op.create_unique_constraint(op.f('sessions_refresh_token_key'), 'sessions', ['refresh_token'], schema='hexa', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='hexa')
    op.create_index(op.f('idx_sessions_refresh_token'), 'sessions', ['refresh_token'], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_services_machine_id'), table_name='services', schema='hexa')
    op.drop_index(op.f('ix_hexa_services_id'), table_name='services', schema='hexa')
    op.create_index(op.f('idx_services_machine_id'), 'services', ['machine_id'], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_service_status_history_timestamp'), table_name='service_status_history', schema='hexa')
    op.drop_index(op.f('ix_hexa_service_status_history_service_id'), table_name='service_status_history', schema='hexa')
    op.drop_index(op.f('ix_hexa_service_status_history_id'), table_name='service_status_history', schema='hexa')
    op.create_index(op.f('idx_svc_hist_timestamp'), 'service_status_history', [sa.literal_column('timestamp DESC')], unique=False, schema='hexa')
    op.create_index(op.f('idx_svc_hist_service_id'), 'service_status_history', ['service_id'], unique=False, schema='hexa')
    op.create_index(op.f('idx_svc_hist_composite'), 'service_status_history', ['service_id', sa.literal_column('timestamp DESC')], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_scheduler_runs_started_at'), table_name='scheduler_runs', schema='hexa')
    op.drop_index(op.f('ix_hexa_scheduler_runs_job_id'), table_name='scheduler_runs', schema='hexa')
    op.drop_index(op.f('ix_hexa_scheduler_runs_id'), table_name='scheduler_runs', schema='hexa')
    op.create_index(op.f('idx_scheduler_runs_job_id'), 'scheduler_runs', ['job_id'], unique=False, schema='hexa')
    op.create_index(op.f('idx_scheduler_runs_composite'), 'scheduler_runs', ['job_id', sa.literal_column('started_at DESC')], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_scheduler_jobs_machine_id'), table_name='scheduler_jobs', schema='hexa')
    op.drop_index(op.f('ix_hexa_scheduler_jobs_id'), table_name='scheduler_jobs', schema='hexa')
    op.create_index(op.f('idx_scheduler_jobs_machine_id'), 'scheduler_jobs', ['machine_id'], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_projects_name'), table_name='projects', schema='hexa')
    op.drop_index(op.f('ix_hexa_projects_id'), table_name='projects', schema='hexa')
    op.create_unique_constraint(op.f('projects_name_key'), 'projects', ['name'], schema='hexa', postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_hexa_machines_id'), table_name='machines', schema='hexa')
    op.drop_index(op.f('ix_hexa_machines_environment_id'), table_name='machines', schema='hexa')
    op.create_index(op.f('idx_machines_environment_id'), 'machines', ['environment_id'], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_machine_metrics_timestamp'), table_name='machine_metrics', schema='hexa')
    op.drop_index(op.f('ix_hexa_machine_metrics_machine_id'), table_name='machine_metrics', schema='hexa')
    op.drop_index(op.f('ix_hexa_machine_metrics_id'), table_name='machine_metrics', schema='hexa')
    op.create_index(op.f('idx_metrics_timestamp_desc'), 'machine_metrics', [sa.literal_column('timestamp DESC')], unique=False, schema='hexa')
    op.create_index(op.f('idx_metrics_machine_id'), 'machine_metrics', ['machine_id'], unique=False, schema='hexa')
    op.create_index(op.f('idx_metrics_composite'), 'machine_metrics', ['machine_id', sa.literal_column('timestamp DESC')], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_logs_timestamp'), table_name='logs', schema='hexa')
    op.drop_index(op.f('ix_hexa_logs_severity'), table_name='logs', schema='hexa')
    op.drop_index(op.f('ix_hexa_logs_service_id'), table_name='logs', schema='hexa')
    op.drop_index(op.f('ix_hexa_logs_machine_id'), table_name='logs', schema='hexa')
    op.drop_index(op.f('ix_hexa_logs_id'), table_name='logs', schema='hexa')
    op.create_index(op.f('idx_logs_timestamp'), 'logs', [sa.literal_column('timestamp DESC')], unique=False, schema='hexa')
    op.create_index(op.f('idx_logs_severity'), 'logs', ['severity'], unique=False, schema='hexa')
    op.create_index(op.f('idx_logs_service_id'), 'logs', ['service_id'], unique=False, schema='hexa')
    op.create_index(op.f('idx_logs_query'), 'logs', ['machine_id', 'log_type', sa.literal_column('timestamp DESC')], unique=False, schema='hexa')
    op.create_index(op.f('idx_logs_machine_id'), 'logs', ['machine_id'], unique=False, schema='hexa')
    op.alter_column('logs', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='hexa')
    op.drop_index(op.f('ix_hexa_incidents_status'), table_name='incidents', schema='hexa')
    op.drop_index(op.f('ix_hexa_incidents_started_at'), table_name='incidents', schema='hexa')
    op.drop_index(op.f('ix_hexa_incidents_id'), table_name='incidents', schema='hexa')
    op.drop_index(op.f('ix_hexa_incidents_environment_id'), table_name='incidents', schema='hexa')
    op.create_index(op.f('idx_incidents_status'), 'incidents', ['status'], unique=False, schema='hexa')
    op.create_index(op.f('idx_incidents_started'), 'incidents', [sa.literal_column('started_at DESC')], unique=False, schema='hexa')
    op.create_index(op.f('idx_incidents_environment_id'), 'incidents', ['environment_id'], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_heartbeats_timestamp'), table_name='heartbeats', schema='hexa')
    op.drop_index(op.f('ix_hexa_heartbeats_id'), table_name='heartbeats', schema='hexa')
    op.drop_index(op.f('ix_hexa_heartbeats_agent_id'), table_name='heartbeats', schema='hexa')
    op.create_index(op.f('idx_heartbeats_timestamp_desc'), 'heartbeats', [sa.literal_column('timestamp DESC')], unique=False, schema='hexa')
    op.create_index(op.f('idx_heartbeats_agent_timestamp'), 'heartbeats', ['agent_id', sa.literal_column('timestamp DESC')], unique=False, schema='hexa')
    op.create_index(op.f('idx_heartbeats_agent_id'), 'heartbeats', ['agent_id'], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_environments_project_id'), table_name='environments', schema='hexa')
    op.drop_index(op.f('ix_hexa_environments_id'), table_name='environments', schema='hexa')
    op.create_index(op.f('idx_environments_project_id'), 'environments', ['project_id'], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_api_checks_id'), table_name='api_checks', schema='hexa')
    op.drop_index(op.f('ix_hexa_api_checks_environment_id'), table_name='api_checks', schema='hexa')
    op.create_index(op.f('idx_api_checks_environment_id'), 'api_checks', ['environment_id'], unique=False, schema='hexa')
    op.alter_column('api_checks', 'headers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='hexa')
    op.drop_index(op.f('ix_hexa_api_check_history_timestamp'), table_name='api_check_history', schema='hexa')
    op.drop_index(op.f('ix_hexa_api_check_history_id'), table_name='api_check_history', schema='hexa')
    op.drop_index(op.f('ix_hexa_api_check_history_api_check_id'), table_name='api_check_history', schema='hexa')
    op.create_index(op.f('idx_api_check_history_timestamp'), 'api_check_history', [sa.literal_column('timestamp DESC')], unique=False, schema='hexa')
    op.create_index(op.f('idx_api_check_history_fk'), 'api_check_history', ['api_check_id'], unique=False, schema='hexa')
    op.create_index(op.f('idx_api_check_history_composite'), 'api_check_history', ['api_check_id', sa.literal_column('timestamp DESC')], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_alerts_service_id'), table_name='alerts', schema='hexa')
    op.drop_index(op.f('ix_hexa_alerts_resolved_at'), table_name='alerts', schema='hexa')
    op.drop_index(op.f('ix_hexa_alerts_machine_id'), table_name='alerts', schema='hexa')
    op.drop_index(op.f('ix_hexa_alerts_incident_id'), table_name='alerts', schema='hexa')
    op.drop_index(op.f('ix_hexa_alerts_id'), table_name='alerts', schema='hexa')
    op.drop_index(op.f('ix_hexa_alerts_api_check_id'), table_name='alerts', schema='hexa')
    op.drop_index(op.f('ix_hexa_alerts_alert_rule_id'), table_name='alerts', schema='hexa')
    op.create_index(op.f('idx_alerts_unresolved'), 'alerts', ['resolved_at'], unique=False, schema='hexa', postgresql_where='(resolved_at IS NULL)')
    op.create_index(op.f('idx_alerts_service_id'), 'alerts', ['service_id'], unique=False, schema='hexa')
    op.create_index(op.f('idx_alerts_machine_id'), 'alerts', ['machine_id'], unique=False, schema='hexa')
    op.create_index(op.f('idx_alerts_incident_id'), 'alerts', ['incident_id'], unique=False, schema='hexa')
    op.create_index(op.f('idx_alerts_api_check_id'), 'alerts', ['api_check_id'], unique=False, schema='hexa')
    op.create_index(op.f('idx_alerts_alert_rule_id'), 'alerts', ['alert_rule_id'], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_alert_rules_id'), table_name='alert_rules', schema='hexa')
    op.drop_index(op.f('ix_hexa_alert_rules_environment_id'), table_name='alert_rules', schema='hexa')
    op.create_index(op.f('idx_alert_rules_environment_id'), 'alert_rules', ['environment_id'], unique=False, schema='hexa')
    op.drop_index(op.f('ix_hexa_agents_token_hash'), table_name='agents', schema='hexa')
    op.drop_index(op.f('ix_hexa_agents_machine_id'), table_name='agents', schema='hexa')
    op.drop_index(op.f('ix_hexa_agents_id'), table_name='agents', schema='hexa')
    op.create_index(op.f('idx_agents_token_hash'), 'agents', ['token_hash'], unique=False, schema='hexa')
    op.create_index(op.f('idx_agents_machine_id'), 'agents', ['machine_id'], unique=False, schema='hexa')
    op.create_unique_constraint(op.f('agents_token_hash_key'), 'agents', ['token_hash'], schema='hexa', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('agents_machine_id_key'), 'agents', ['machine_id'], schema='hexa', postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_hexa_phase1_storage_metrics_report_id'), table_name='phase1_storage_metrics', schema='hexa')
    op.drop_index(op.f('ix_hexa_phase1_storage_metrics_id'), table_name='phase1_storage_metrics', schema='hexa')
    op.drop_table('phase1_storage_metrics', schema='hexa')
    op.drop_index(op.f('ix_hexa_phase1_gpu_metrics_report_id'), table_name='phase1_gpu_metrics', schema='hexa')
    op.drop_index(op.f('ix_hexa_phase1_gpu_metrics_id'), table_name='phase1_gpu_metrics', schema='hexa')
    op.drop_table('phase1_gpu_metrics', schema='hexa')
    op.drop_index(op.f('ix_hexa_phase1_metric_reports_timestamp'), table_name='phase1_metric_reports', schema='hexa')
    op.drop_index(op.f('ix_hexa_phase1_metric_reports_machine_id'), table_name='phase1_metric_reports', schema='hexa')
    op.drop_index(op.f('ix_hexa_phase1_metric_reports_id'), table_name='phase1_metric_reports', schema='hexa')
    op.drop_table('phase1_metric_reports', schema='hexa')
    # ### end Alembic commands ###
